### ISSUE TITLE
can you get global from 'global.ts'?

### ISSUE THREAD

**Issue by ghost** [dojo/core#102] opened 2016-01-05 16:18 UTC
i got an undeifne in amd style

**Comment by kitsonk** [comment] 2016-01-05 16:28
What version of TypeScript are you using, what AMD loader?

Likely a duplicate of #100

**Comment by kitsonk** [comment] 2016-01-06 12:40
I fixed #100 and I am pretty sure that was what you were running into.  If not, if you could provide more details, I will reopen.

**Closed as completed by kitsonk** 2016-01-06 12:40 UTC
Labels: duplicate
