### ISSUE TITLE
Debounce/Throttle test cases too fragile

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#107] opened 2016-01-13 10:29 UTC
It seems that randomly we get failures to the [throttle and debounce test cases](https://travis-ci.org/dojo/core/builds/102064338#L174).  Usually Firefox but sometimes other platforms.

We should find a way to make them more robust.

**Comment by msssk** [comment] 2016-02-20 01:42
I've been testing this and looking into it, and there are a few issues:

### Severely restricted test environments

When using `setTimeout` in tests, we are usually giving fairly generous padding time (to the detriment of the total run time of the test suite), but it's clearly not enough for some of the atrociously underpowered test environments. `setTimeout` simply guarantees that the code will not be executed **before** the specified delay, but it may run _well after_ the specified delay.

In order to reproduce these timing issues I had to limit the CPU in my VM (IE10/Win7) to 1%. This suggests that the test infrastructure we are using continues to be significantly overtaxed, and not well-suited to timing-sensitive testing.

I think what we should do is to use very tight delays, so that in the best case, the test case will run to completion quickly. Since we necessarily have a test timeout (when using `this.async(timeout)`), I think we're probably better off replacing the approach of waiting a seemingly reasonable amount of time and checking to see if test conditions have been met with an assertion, and should instead resolve the deferred from `this.async` as soon as the function that meets the test conditions finishes executing. The downside to this approach is that when a test fails, we get no tailored failure message, just "Timeout reached".

### Non-optimal use of `setTimeout` in `core/util`

Because of the unreliability of timers in JavaScript, I think we should avoid them as much as possible. For example, look at the way `throttle` currently works:
https://github.com/dojo/core/blob/a9e5ef3dc4bf72a376cbe7e7e2fc90c38697260b/src/util.ts#L63-L65

If a throttle delay of 50ms is specified, the throttle guard won't be reset for _at least_ 50ms - but maybe longer. The result is that the function may be throttled by 50ms, or 80ms, or who knows how long.

I think a better approach, which I have started work on implementing, is to keep a `lastRun` tick and compare the ticks of subsequent calls to the `lastRun` tick. As long as 50ms has transpired then subsequent invocations will be allowed to execute.

**Comment by kitsonk** [comment] 2016-02-22 09:27
> I think a better approach, which I have started work on implementing, is to keep a lastRun tick and compare the ticks of subsequent calls to the lastRun tick. As long as 50ms has transpired then subsequent invocations will be allowed to execute.

Actually, now that you say it, it does sound rather surprising that we used timeouts for these type of functions.  Thanks!

**Comment by kfranqueiro** [comment] 2016-02-22 13:46
While that might be a possible point for `throttle`, I would think that `setTimeout` is _required_ for how `debounce` and `throttleAfter` work, so I'm not sure there's much point to switching it out for one of the three.

**Comment by msssk** [comment] 2016-02-27 01:42
Agreed, I see no way of implementing `debounce` or `throttleAfter` without `setTimeout`.

However, I think `throttle` is the most commonly useful function, so it's definitely worthwhile making its behavior as correct as possible (keeping in mind JS runtimes do not provide a real-time environment).

I'm curious about the utility (and implementation) of `throttleAfter`. From reading the [code comments](by using time diffs where possible) I get the impression that the goal is:

```
throttle: 100
0                    100                  200
|--------------------|--------------------|
^                    ^                    ^
execute -  ignore  - execute -  ignore  - execute

throttleAfter: 100
0                    100                  200
|--------------------|--------------------|
                     ^                    ^
ignore       -       execute -  ignore  - execute
```

If this is the case, this is functionally the same as simply delaying the initial execution, in which case `throttleAfter` can be implemented with a single initial `setTimeout` followed by applying the normal `throttle`.

The way `throttleAfter` is actually implemented is that it has no repeating interval.
- Initial execution is delayed by 100 ms
- Subsequent calls during the 100 ms delay are ignored
- After 100 ms passes and execution occurs, the callback is ready to be executed again, **however**, regardless of whether it is called immediately after the previous execution cleared the timer, 90 ms after, or an hour later, it will still have its execution delayed by 100 ms.

**Comment by kfranqueiro** [comment] 2016-02-27 02:03
There is one very important distinction you are missing in your diagrams: `throttle` will _not_ execute at the 200ms mark (assuming the last actual call happened at let's say 150ms).

dgrid uses `throttleAfter` (or in its case, `util/misc.throttleDelayed`, but same concept) on window resize events, and mouse move events for ColumnResizer, because the value at the very end is what matters, but we also don't want to `debounce` since that could look unresponsive.

**Comment by msssk** [comment] 2016-02-27 02:16
I left out an important assumption: I'm assuming that the functions are in fact being used to _throttle_, and so are being called repeatedly throughout the duration.

With that assumption, is my description correct or am I missing something?

We do need to consider behavior when the functions are _not_ being called frequently at a shorter interval than the delay - I'll have to look at that some more.

**Comment by kfranqueiro** [comment] 2016-02-27 02:19
That assumption is correct, and my correction to your first diagram still applies.  (My examples involving resize/mousemove are certainly operations that would be expected to fire far more often than the throttle delay, which is the point of using `throttleAfter` on them.)

If you wanted to play devil's advocate for demonstration purposes, you could probably go into the dgrid ColumnResizer test page and fiddle around resizing columns after switching the module's `throttleDelayed` call to just plain `throttle`.  You should observe that if you don't pause your mouse cursor before dropping, it may seem to drop slightly off from where you actually last moved.  Upping its delay would probably also make it more noticeable.

**Comment by msssk** [comment] 2016-02-27 20:44
So is the intention of `throttleAfter` simply to ensure the following?
- the function is not called more frequently than specified by `delay`
- if the function is called when execution is suspended during the delay, but then no longer called, it should be executed one final time

If that is the intention, I would think we would still want to allow execution within the window set by `delay`, rather than always delaying execution of the function by a certain amount.

Consider these scenarios with the current implementation:

Scenario 1:
- delay of 100 ms
- call function at 100 ms: it gets executed
- call function at 110 ms: it does not get executed, but is set to execute at 210 ms

Scenario 2:
- delay of 100 ms
- call function at 100 ms: it gets executed
- call function at 190 ms: it does not get executed, but is set to execute at 290 ms

I would think in both scenarios it should be executed at 200 ms.

As an aside, I changed [this](https://github.com/SitePen/dgrid/blob/50e16d82ef0601f24241d2d49aea136ed5d3839b/extensions/ColumnResizer.js#L320) to `throttle` and didn't notice any appreciable difference. For current/future versions of dgrid, I wonder if we might consider `requestAnimationFrame` and live column resizing?

**Comment by kitsonk** [comment] 2016-03-11 11:05
So, if I am understanding this at the moment...
- The tests are "fragile" but only because the cloud testing providers have some severely constrained resources at times and any real modification to the tests from where there are at would likely just make the tests meaningless.
- There _might_ be some improvements we can make to these functions, as long as the demonstrate the correct functional behaviour.  (If this is the case, we should open another issue to track that).

If I am correct on the first bullet point we should close this issue.

**Comment by msssk** [comment] 2016-03-11 18:19
The tests are fragile because they're testing something not guaranteed by JS runtimes. I don't think we should test it. The contract for `setTimeout` is "I will run this _not before_ the specified delay". But there's no guarantee how soon _after_ the specified delay it will be run. In practice, we are often dependent on it running very closely to the specified delay to achieve desirable behavior & performance, but it's not something we can reasonably include in automated tests.
- To close this issue, I believe we should remove some of our tests ([I have](https://github.com/msssk/core/commit/cbcce20d9dc1b12aaa76a6e4d78e2d83c6d5bc4d)), and improve some of our other tests so they can complete as fast as possible while still running correctly in severely resource-limited environments. I've updated some tests, there are more to work on.
- I don't think `throttle` should ever be implemented with `setTimeout` - I've [updated it](https://github.com/msssk/core/commit/cbcce20d9dc1b12aaa76a6e4d78e2d83c6d5bc4d) to use time diffs. `debounce` and `throttleAfter` (whose utility evades me) are dependent on `setTimeout`.

**Comment by kfranqueiro** [comment] 2016-03-11 18:21
Out of curiosity, have you tried profiling or using the timeline view to see how much time is spent in the new implementation vs. the old one, if the throttled function gets slammed?

**Comment by msssk** [comment] 2016-03-12 00:52
Thanks Ken, good thought. I previously felt strongly that `throttle` should use time diffs; now I only slightly prefer it. I doubt which implementation is used would have a noticeable effect in real-world scenarios.

I profiled a simple test of the two implementations throttling the `mousemove` event and they appeared very similar:
- 1.2% CPU (with an extra 0.6% for executing `setTimeout` itself) for `setTimeout`
- 1.6% CPU for time diffs

However, with [jsperf benchmarking](http://jsperf.com/throttle-timeout) the `setTimeout` implementation sees a significant performance advantage. Generally speaking I think _correct_ should win over _performant_, but in the case of throttling I think the _correct_ behavior is "provide the end user a pleasant UI experience". In the case of a decently performant computer `setTimeout` will execute the callback at, or very close to, the specified delay. In cases where CPU power is so low that `setTimeout` becomes unreliable in this respect, the time diff approach might end up being more accurate, but performance is already completely shot anyway, so UI performance and user experience is going to be trash regardless of which implementation is used.

I'm no longer pushing for the `throttle` implementation to be changed, but we do clearly need to update our tests to work in severely resource-constrained environments, so I will continue wrapping that up.

**Closed as completed** 2016-03-21 07:47 UTC
