### ISSUE TITLE
version alpha.7 does not work under nodejs

### ISSUE THREAD

**Issue by taoqf** [dojo/core#166] opened 2016-05-26 12:37 UTC
i upgrade to alpha7today, but i find it can not work in nodejs.
because require can not load js file in dist/umd/
and i cannot just `import {on} from 'dojo-core';` in ts.
alph5 works as i know.

**Comment by kitsonk** [comment] 2016-05-26 13:21
The ability to import modules that way was never intentional, it was accidental that it worked with CJS that way.

When we realigned the distributions, we wanted to make them work better with CJS (without TypeScript).  Therefore we added `index.js` to the root of the package and added `"main": "index.js"` to the `package.json`.  The `index.js` points at `/dist/umd/main.js` which exports all the "public" APIs of a package.  Therefore `require('dojo-core')` using the CJS loader in node, would return this object.

That combined with us actually fixing the `typings` property in the `package.json`, causes problems with TypeScript 1.8 when acquiring the type using `node` module resolution, because it is expecting "UMD" declaration files, not a global `.d.ts` which is what `typings` on the package points at.

Since we do all of our development with the `classic` module resolution and an AMD loader which allows us to easily remap the root of the package, and we are always explicit about which module we are importing from, we didn't realise we broke this behaviour.

At the moment, both of these work in NodeJS with `alpha.7`:

``` javascript
var on1 = require('dojo-core/dist/umd/on').default;
var on2 = require('dojo-core').on;
```

On the TypeScript side, it is a bit of a challenge.  With `moduleResolution` set to `node` (the default), TypeScript complains that the typings are "wrong" (because it is expecting "UMD" `.d.ts` instead of a global one).  With classic resolution, and a reference to the `.d.ts` file, it can resolve the modules, but what it outputs cannot be resolved at run-time by the CJS loader.

In order to fix this, we need to transition to the "UMD" modules as described in dojo/meta#46.  It was likely going to need to happen anyways, but obviously this increases the necessity.

Another workaround is to use an AMD loader, like the `dojo/loader` under NodeJS.  There are parts of `dojo-core` that won't work without an AMD loader that supports the AMD Plugin API, and there is no way to provide that functionality with the CJS loader and it is debatable whether SystemJS will continue to support their plugin API since it is part of the ESM standard.  Therefore for the foreseeable future we will continue to build Dojo 2 expecting that there is an AMD module loader.

**Comment by taoqf** [comment] 2016-05-26 14:12
i'm sorry to see this.
i do not want an amd loader in nodejs, i do not think it is necessary.
i didn't plan to use amd loader if only i have to.
without dojo-loader, i tried, and failed to import dojo-core/on. i have tried all the modules and resolutions.

**Comment by taoqf** [comment] 2016-05-26 14:13
and i go back to version alpha.5 now.

**Comment by taoqf** [comment] 2016-05-26 14:22
i do not want an amd loader bacause it did not work well with pm2(dojo1.x)
and i don't think i really need and amd loader under nodejs.

**Comment by kitsonk** [comment] 2016-05-26 14:27
> i do not want an amd loader in nodejs, i do not think it is necessary.

Why do you think it is not necessary?  How do you achieve feature detection module loading (e.g. core/has) and things like dynamically loading resource bundles (like will be in dojo/i18n)?  How do you achieve module substitution, like is done with AMD mapping?

Again, SystemJS provides these features, but you are indicating that you aren't using that either.  The only thing CJS provides is the ability to potentially load and process non JavaScript resources through a "registry" which is solved via plugin-ins in AMD, but then the resource IDs don't then change between NodeJS and the browser with AMD.

**Comment by taoqf** [comment] 2016-05-26 14:46
Need i use i18n? i don't think so. At least i don't need it under nodejs.
I won't use has(as a plugin), text under nodejs
I would rather use fs or require in nodejs directly.
I do not want dojo2 to be another dojo1.x.
When i use dojo1.x,  i do many things to make the my code to be same in browser and nodejs,
and i was proud of that at one time.
But i changed my idea recently, i don't think i need to do this again, i did this just becuase dojo1.x leaded me to.
I would rather to go the easier way, not just have the same code.
I think JQuery is popular becuase it is easy to learn and use, is there something we could learn from JQuery?

**Comment by taoqf** [comment] 2016-05-26 14:49
It is very late here(i am in china). I will check the message tomorrow.

**Comment by kitsonk** [comment] 2016-05-26 16:05
> Need i use i18n? i don't think so. At least i don't need it under nodejs.

You don't but, we aren't building a toolkit just for your use cases.

Let me be clear, I marked this as a bug, because we want to support CJS as far as is possible and we need to fix it so people can use Dojo 2 with just the NodeJS loader, but there are very specific features that have been delivered that need to work a) seamlessly between NodeJS and a Browser and b) can't be delivered with just the NodeJS CJS loader.

I would argue that Dojo 2 is likely not the best choice if you are just using server side NodeJS.  While I would love Dojo 2 to have wide adoption, it won't be everything to everyone.  The main goals of Dojo 2 are to:
- Build data-heavy web applications.
- Build web applications that work well in large scale development environments.
- Providing important functionality for web applications that are important to enterprises (e.g. internationalisation, accessibility, security)

That means it should work well under NodeJS, but really in support of larger web applications.  I don't want to discourage you from continuing to use Dojo 2, but I want to make sure you have the right expectations about where it will head.

**Comment by dylans** [comment] 2016-05-26 16:06
I don't think the future of node.js is to use require(), it's to use ES6 modules with import and export. Until we get there though, it's a rough path along the way. Users of Dojo 2 will generally not use AMD, even if Dojo 2 internally uses AMD due to imperfections or limitations with current ES6 module loading.

Dojo 2 is not like Dojo 1, and I think you're not quite understanding what we're saying. Please try to be patient, we're still in alpha and we're trying to make something powerful work, and there's a lot of complexity and rough edges to smooth over.

Dojo is not jQuery, nor should it try to be. As they say, simple + simple + simple = simple, but easy + easy + easy = complex. Simplicity for us comes from the elegance of good patterns over a broad code base, rather than just picking a bunch of things that seem easy but inconsistent, but then become complex when trying to use them together. (And to be clear, I'm not saying or implying that jQuery is bad by my statement, just that "be more like jQuery" isn't what defines us!)

**Comment by taoqf** [comment] 2016-05-27 03:10
Thank you for your advice. @kitsonk 
Like @dylans says, maybe i went too far and was impatient.

**Comment by kitsonk** [comment] 2016-06-02 13:24
As a temporary fix while we transition to UMD Definition Files, we will add a "main" module to the typings definition that gets exported in the package.  We should have done this from the get go, but I had forgotten about that feature in `dts-generator`.  In each package we will export the public facing APIs and therefore `import * as dojoCore from 'dojo-core';` would import the whole of `dojo-core` under CJS or AMD and `import { on } from 'dojo-core';` will work properly in TypeScript and will work as designed for CJS or AMD.

It is still recommended that instead of importing the whole of the package, individuals still import from the specific module (e.g. `import on from 'dojo-core/on';`) the problem is that will not work properly at run-time for CJS, though it would work with a properly configured AMD or SystemJS loader.

**Closed as completed** 2016-06-02 13:31 UTC
Labels: bug

**Comment by kitsonk** [comment] 2016-09-07 18:08
As an update, this solution didn't work exactly as we would have liked it to work, but now the public namespace packages published to NPM now contain a format that is easy to consume with a CommonJS loader (e.g. NodeJS) or an AMD loader.  Also because we transition to UMD definition files for these packages, type acquisition under TypeScript 2 is greatly improved.
